title: Antrikshy.com
url: https://antrikshy.com
code:
  title: code.Antrikshy
  tagline: "Notes, tinkerings, experiments"
  url: https://antrikshy.com/code
film:
  title: film.Antrikshy
  tagline: "Thoughts on film and games"
  url: https://antrikshy.com/film

baseurl: /

permalink: none
paginate: 3
paginate_path: "/code/page:num"
excerpt_separator: "<!--more-->"

author:
  name: Antriksh Yadav
  url: https://antrikshy.com
  email: antrikshy@gmail.com
  twitter: Antrikshy

github:
  repo: https://github.com/Antrikshy/antrikshy.github.io
personal_external_links:
  linkedin: 'https://www.linkedin.com/in/antriksh-yadav-b9a39924'
  twitter: 'https://twitter.com/Antrikshy'
  github: 'https://github.com/Antrikshy'

# Build settings
# plugins:
# Listed in the :jekyll_plugins group in the Gemfile.
# See: https://jekyllrb.com/docs/plugins/installation/
markdown: kramdown
highlighter: rouge
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge
# This makes the local preview server accessible over LAN
host: 0.0.0.0

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
exclude:
#   - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
