# Dependencies
markdown:         kramdown
highlighter:      true
plugins:          [jekyll-paginate, jekyll-seo-tag]

# Permalinks
permalink:        none

# Setup
title:            code.Antrikshy
tagline:          'Notes, tinkerings, experiments'
url:              https://antrikshy.com/
paginate:         3
paginate_path:    "blog/page:num"
excerpt_separator: "<!--more-->"
baseurl:          /
highlighter:      rouge
author:
  name:           Antriksh Yadav
  url:            https://antrikshy.com
  email:          antrikshy@gmail.com
  twitter:        Antrikshy

# Custom vars
github:
  repo:           https://github.com/Antrikshy/antrikshy.github.io
blog_masthead_pages:       
  Entries:        '/entries'
  Feed:           '/atom.xml'
  About:          '/about'
  Projects:       '/projects'
  Resume:         '/resume'
personal_external_links:
  linkedin:        'https://www.linkedin.com/profile/view?id=AAIAAAUKQGYBw5-mPuOlHHK_eit5XwiREBrMxzM'
  twitter:         'https://twitter.com/Antrikshy'
  github:          'https://github.com/Antrikshy'
